### ISSUE TITLE
Find nodes that have a specific tag

### ISSUE THREAD

**Issue by onato** [sammerry/node-mongosm#19]
It seems that with the current schema there is not way for find all places.

```
{
  "_id" : 204648, 
  "tags" : { 
    "wikipedia" : "en:Wellington", 
    "place" : "city", 
  …
},
{
  "_id" : 649684, 
  "tags" : { 
    "tourism" : "viewpoint"
  },
  …
}, 
```

Would it not make more sense to change the schema to…

```
{
  "_id" : 204648, 
  "tags" : [
    {"key":"wikipedia", "value": "en:Wellington"}, 
    {"key":"place", "value": "city"}, 
    …
  ]
},
```

This would enable me to ask the following: 

```
db.nodes.find({'tags.key' : 'place'})
```

Or am I missing something?

**Comment by sammerry** [comment]
Sorry for the late reply. You can use an exists query which might be faster. Something like `db.nodes.find( { place : { $exists : true } } );`
